name: Run Tests and Lint

on: push

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup environment
      run: task setup
    - name: Run Tests
      run: task test
    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v2
    - name: Run Lint
      run: task lint
