name: bump-version
on:
  push:
    branches:
      - main
permissions:
    contents: write
    pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.TOKEN }}
          release-type: go

      - name: merge-pr
        if: steps.release.outputs.pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const pr = ${{ steps.release.outputs.pr }};
            if (pr && pr.number) {
              github.rest.pulls.merge({
                pull_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              });
            }
